import {BALANCE as B,TYRES} from '../../data/config.js';
import {CIRCUITS} from '../../data/circuits.js';
import {random,clamp} from '../core/random.js';
import {bike,lineup,staffSkill,readiness} from '../state/career.js';
import {category,spend} from '../systems/finance.js';
export const currentCircuit=s=>CIRCUITS.find(c=>c.id===s.calendar[s.round]);
export const log=(q,text)=>{q.feed.unshift({time:q.elapsed,text});q.feed=q.feed.slice(0,50);};
export function enterWeekend(s){if(s.phase!=='management')throw Error('Uma etapa já está em andamento.');const missing=readiness(s);if(missing.length)throw Error(missing.join(' • '));spend(s,B.travelCost*category(s).cost,'travel','Transporte para '+currentCircuit(s).name);s.phase='practice';s.weekend={setup:[50,50,50],tyre:'medium',pace:0,practice:null,qualifying:null,grid:null,health:100,feedback:null,runs:[]};}
export function makeGrid(result,penalties=[]){const entries=result.map((r,i)=>({...r,qualifyingPosition:i+1,penalty:penalties.find(p=>p.riderId===r.riderId)?.places||0}));entries.sort((a,b)=>(a.qualifyingPosition+a.penalty)-(b.qualifyingPosition+b.penalty)||a.qualifyingPosition-b.qualifyingPosition);return entries.map((r,i)=>({...r,gridPosition:i+1}));}
export function startSession(s,kind){if(s.session)throw Error('Encerre a sessão atual.');if(s.phase!==kind||!['practice','qualifying','race'].includes(kind))throw Error('Ordem de sessão inválida.');const circuit=currentCircuit(s);const q={kind,state:'GREEN',elapsed:0,seed:Math.floor(random(s)*4294967295),duration:kind==='practice'?B.practiceSeconds:kind==='qualifying'?B.qualifyingSeconds:0,laps:category(s).laps,entries:[],feed:[],incidents:[],weather:{wet:random(s)<circuit.rain?.65:.02,temp:circuit.temp},nextWeather:B.weatherInterval,flagUntil:0,redRemaining:0};
 const all=[...lineup(s).map(r=>({r,teamId:'player'})),...s.teams.flatMap(t=>lineup(s,t.id).map(r=>({r,teamId:t.id})))];
 all.forEach(({r,teamId},i)=>{const grid=s.weekend.grid?.find(g=>g.riderId===r.id)?.gridPosition||i+1;const isPlayer=teamId==='player';q.entries.push({riderId:r.id,teamId,number:r.number,attributes:{...r.attributes},bike:bike(s,teamId),setup:isPlayer?[...s.weekend.setup]:circuit.setup.map(v=>clamp(v+(random(q)-.5)*36,0,100)),pace:isPlayer?s.weekend.pace:0,tyre:isPlayer?s.weekend.tyre:q.weather.wet>.4?'wet':'medium',wear:0,temperature:45,health:isPlayer?s.weekend.health:100,progress:0,lap:0,lapStart:0,lapTime:0,last:null,best:null,sectors:[],lastSectors:[],sectorTime:0,segment:0,status:kind==='race'?'TIMED_LAP':'IN_GARAGE',delay:kind==='race'?(grid-1)*.14+(100-r.attributes.start)*.006:0,releaseAt:15+i*6+random(q)*12,boxRequested:false,plannedLaps:3,runLaps:0,runs:[],task:0,finishedAt:null,grid,variance:1,mechanic:isPlayer?staffSkill(s,'mechanic'):70});});
 s.session=q;log(q,kind==='race'?'Luzes apagadas. Boa corrida!':'Pista aberta. Escolha o momento de liberar suas motos.');return q;
}
export function command(s,riderId,action,value){const q=s.session;if(!q||q.state==='POST_SESSION')throw Error('Não há sessão ativa.');const e=q.entries.find(x=>x.riderId===riderId&&x.teamId==='player');if(!e)throw Error('Piloto não encontrado.');if(action==='pace'){if(![-1,0,1].includes(+value))throw Error('Ritmo inválido.');e.pace=+value;log(q,'Ritmo de #'+e.number+': '+['conservar','equilibrado','atacar'][e.pace+1]);}else if(action==='out'){if(e.status!=='IN_GARAGE'||e.task>0)throw Error('A moto ainda não está pronta.');if(q.elapsed>=q.duration&&q.kind!=='race')throw Error('Cronômetro encerrado.');release(e,q);log(q,'#'+e.number+' liberado da garagem.');}else if(action==='box'){e.boxRequested=true;log(q,'#'+e.number+': box ao fim desta volta.');}else if(action==='tyre'){if(!TYRES[value])throw Error('Pneu inválido.');if(e.status!=='IN_GARAGE')throw Error('Chame o piloto aos boxes primeiro.');e.tyre=value;e.wear=0;e.temperature=45;e.task=B.garageSeconds*(110-e.mechanic)/40;log(q,'Mecânicos trocando pneus de #'+e.number);}}
function release(e,q){e.status=q.kind==='race'?'TIMED_LAP':'OUT_LAP';e.lapStart=q.elapsed;e.lapTime=0;e.sectorTime=0;e.segment=0;e.progress=q.kind==='race'?e.progress:0;e.runLaps=0;e.boxRequested=false;e.variance=1;}
export function setSetup(s,values){if(!s.weekend||!values.every(v=>Number.isFinite(v)&&v>=0&&v<=100)||values.length!==3)throw Error('Acerto inválido.');if(s.phase==='grid'||s.phase==='race'||s.phase==='result')throw Error('Acerto fechado após a classificação.');if(s.session){const players=s.session.entries.filter(e=>e.teamId==='player');if(players.some(e=>e.status!=='IN_GARAGE'))throw Error('Recolha as duas motos para alterar o acerto.');for(const e of players){e.setup=[...values];e.task=B.garageSeconds*(110-e.mechanic)/40;}log(s.session,'Engenharia iniciou ajustes nas duas motos.');}s.weekend.setup=[...values];}
export function factors(e,c,q,seg){const a=e.attributes,b=e.bike;const bikeFit=seg.type==='straight'?b.speed:seg.type==='corner'?(b.braking+b.agility)/2:b.traction;const riderFit=seg.type==='straight'?a.speed:seg.type==='corner'?(a.braking+a.qualifying)/2:a.traction;const setupDistance=e.setup.reduce((sum,v,i)=>sum+Math.abs(v-c.setup[i]),0)/3;const tyre=TYRES[e.tyre];const wet=q.weather.wet;const weather=wet*.12+(tyre.wet?Math.max(0,.35-wet)*.2:Math.max(0,wet-.2)*.36);const wear=Math.pow(e.wear/100,2)*.07+(e.wear>78?(e.wear-78)*.003:0);const temp=Math.abs(e.temperature-(tyre.wet?65:85))*.0002;return {bike:(75-bikeFit)*B.bikeWeight,rider:(75-riderFit)*B.riderWeight,setup:setupDistance*B.setupWeight,tyre:tyre.grip+wear+temp,weather:weather+wet*(80-a.wet)*.0007,health:(100-e.health)*.0004,pace:-e.pace*B.paceGain,evolution:-Math.min(q.elapsed/100000,.006),variance:(e.variance-1)};}
export function lapFactor(e,c,q,seg){return clamp(1+Object.values(factors(e,c,q,seg)).reduce((a,b)=>a+b,0),.8,1.65);}
function microsegment(c,progress){const p=progress%1;let sum=0;for(const seg of c.segments){sum+=seg.weight;if(p<sum)return seg;}return c.segments.at(-1);}
export function ranking(q){return [...q.entries].sort((a,b)=>q.kind==='race'?((a.status==='RETIRED')-(b.status==='RETIRED')||(a.finishedAt??Infinity)-(b.finishedAt??Infinity)||b.progress-a.progress):((a.best??Infinity)-(b.best??Infinity)||a.grid-b.grid));}
export function redFlag(q){if(q.state==='POST_SESSION')return;q.state='RED';q.redRemaining=15;log(q,'Bandeira vermelha. Sessão interrompida; posições preservadas.');}
export function tick(s,dt=B.tick){const q=s.session;if(!q||q.state==='POST_SESSION')return;const c=currentCircuit(s);if(q.state==='RED'){q.redRemaining-=dt;if(q.redRemaining<=0){q.state='GREEN';log(q,'Pista liberada. Retomada da sessão.');}return;}
 q.elapsed+=dt;if(q.elapsed>=q.nextWeather){q.nextWeather+=B.weatherInterval;const old=q.weather.wet;q.weather.wet=clamp(old+(random(q)-.48)*.18,0,1);if((old>.35)!==(q.weather.wet>.35))log(q,q.weather.wet>.35?'Chuva aumentando. Avalie pneus de chuva.':'A pista está secando. Avalie pneus slick.');}
 if(q.state==='YELLOW_LOCAL'&&q.elapsed>q.flagUntil)q.state='GREEN';
 for(const e of q.entries){if(['RETIRED','FINISHED'].includes(e.status))continue;if(e.status==='IN_GARAGE'){e.task=Math.max(0,e.task-dt);if(q.kind==='race'&&e.task===0)release(e,q);else if(e.teamId!=='player'&&q.elapsed>=e.releaseAt&&e.task===0&&q.elapsed<q.duration-c.baseLap*.5)release(e,q);continue;}
 if(e.delay>0){e.delay-=dt;continue;}
 const seg=microsegment(c,e.progress);if(seg.id!==e.segment){e.segment=seg.id;e.variance=1+(random(q)-.5)*(100-e.attributes.consistency)*.0008;}
 const factor=lapFactor(e,c,q,seg)*(e.status==='OUT_LAP'?1.12:1)*(q.state==='YELLOW_LOCAL'?1.05:1);e.lastFactor=factors(e,c,q,seg);let delta=dt/(c.baseLap*category(s).power*factor);
 // A slower bike cannot be passed without a usable attack opportunity.
 if(q.kind==='race'){const ahead=q.entries.filter(o=>o!==e&&!['RETIRED','IN_GARAGE','FINISHED'].includes(o.status)&&o.progress>e.progress).sort((a,b)=>a.progress-b.progress)[0];if(ahead&&e.progress+delta>=ahead.progress&&ahead.progress-e.progress<.002){const attack=(e.attributes.overtaking-ahead.attributes.defence)/100+seg.opportunity+e.pace*.1;if(q.state==='YELLOW_LOCAL'||random(q)>attack)delta=Math.max(0,ahead.progress-e.progress-.00015);else log(q,'#'+e.number+' supera #'+ahead.number+' no setor '+(Math.floor((e.progress%1)*3)+1)+'.');}}
 const oldProgress=e.progress;e.progress+=delta;e.lapTime+=dt;e.sectorTime+=dt;const oldSector=Math.floor((oldProgress%1)*3),newSector=Math.floor((e.progress%1)*3);if(oldSector!==newSector){e.sectors.push(e.sectorTime);e.sectorTime=0;}
 const compound=TYRES[e.tyre];e.wear=clamp(e.wear+dt*B.wearRate*100*c.abrasion*compound.wear*(1+e.pace*B.paceWear)*(1+(80-e.attributes.tyre)*.008)*(compound.wet&&q.weather.wet<.25?2:1),0,100);e.temperature+=( (compound.wet?65:85)+e.pace*6-e.temperature)*dt*.025;e.health=clamp(e.health-dt*B.healthWear*100*(1+e.pace*.25),0,100);
 const pressure=(1+e.pace*.65)*(1+(100-e.attributes.riskControl)/60)*(1+q.weather.wet*(compound.wet?.2:2))*(1+Math.max(0,e.wear-65)/30)*seg.risk;
 if(random(q)<B.incidentBase*pressure*dt){const terminal=random(q)<.18;e.delay=terminal?0:2+random(q)*5;if(terminal)e.status='RETIRED';q.incidents.push({riderId:e.riderId,time:q.elapsed,type:terminal?'Queda / abandono':'Erro de trajetória'});log(q,'#'+e.number+(terminal?' caiu e abandonou.':' escapou da trajetória e perdeu tempo.'));q.state='YELLOW_LOCAL';q.flagUntil=q.elapsed+12;}
 if(random(q)<B.failureBase*(1+(100-e.bike.reliability)/25)*(1+(100-e.health)/30)*dt){e.status='RETIRED';q.incidents.push({riderId:e.riderId,time:q.elapsed,type:'Falha mecânica'});log(q,'#'+e.number+' abandona por falha mecânica.');}
 if(Math.floor(e.progress)>Math.floor(oldProgress)){e.lap++;const lap=e.lapTime;e.last=lap;e.lastSectors=[...e.sectors];e.sectors=[];if(e.status!=='OUT_LAP'&&e.status!=='RETIRED'){e.best=e.best===null?lap:Math.min(e.best,lap);e.runs.push({lap:e.lap,time:lap,setup:[...e.setup],wear:e.wear,tyre:e.tyre,sectors:[...e.lastSectors]});e.runLaps++;}e.lapTime=0;e.sectorTime=0;e.lapStart=q.elapsed;if(e.status==='OUT_LAP')e.status='TIMED_LAP';
 if(q.kind==='race'&&e.lap>=q.laps&&e.status!=='RETIRED'){e.status='FINISHED';e.finishedAt=q.elapsed;e.progress=q.laps;log(q,'#'+e.number+' recebe a bandeirada.');}
 else if(q.kind!=='race'&&q.elapsed>=q.duration&&e.status!=='RETIRED'){e.status='FINISHED';e.finishedAt=q.elapsed;}
 else if(e.status!=='RETIRED'&&(e.boxRequested||(q.kind!=='race'&&e.runLaps>=e.plannedLaps))){e.status='IN_GARAGE';e.boxRequested=false;e.task=q.kind==='race'?B.tyreStopSeconds:0;e.releaseAt=q.elapsed+30;if(q.kind==='race'){e.wear=0;e.tyre=q.weather.wet>.35?'wet':'medium';log(q,'#'+e.number+' troca para '+TYRES[e.tyre].name+'.');}else log(q,'#'+e.number+' nos boxes. Dados de '+e.runLaps+' volta(s) disponíveis.');}
 }
 if(e.teamId!=='player'&&q.kind==='race'&&((q.weather.wet>.48&&!compound.wet)||(q.weather.wet<.15&&compound.wet)||e.wear>90))e.boxRequested=true;
 }
 const timedDone=q.kind!=='race'&&q.elapsed>=q.duration&&q.entries.every(e=>['FINISHED','RETIRED','IN_GARAGE'].includes(e.status));const raceDone=q.kind==='race'&&q.entries.every(e=>['FINISHED','RETIRED'].includes(e.status));if(timedDone||raceDone||q.elapsed>(q.kind==='race'?q.laps*c.baseLap*3:q.duration+c.baseLap*3)){q.state='POST_SESSION';log(q,'Sessão encerrada. Resultados disponíveis.');}
}
export function finishTimedSession(s){const q=s.session;if(!q||q.state!=='POST_SESSION'||q.kind==='race')throw Error('Aguarde o encerramento da sessão.');const result=ranking(q).map((e,i)=>({riderId:e.riderId,teamId:e.teamId,position:i+1,best:e.best,status:e.status,sectors:e.lastSectors}));s.weekend[q.kind]=result;s.weekend.runs.push(...q.entries.filter(e=>e.teamId==='player').flatMap(e=>e.runs.map(r=>({...r,riderId:e.riderId}))));s.weekend.health=Math.max(70,Math.min(...q.entries.filter(e=>e.teamId==='player').map(e=>e.health)));if(q.kind==='practice'){const c=currentCircuit(s);const skill=staffSkill(s,'engineer');s.weekend.feedback=c.setup.map((v,i)=>clamp(Math.round(v+(random(s)-.5)*(100-skill)*.7),0,100));s.phase='qualifying';}else{s.weekend.grid=makeGrid(result);s.phase='grid';}s.session=null;return result;}
