import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createCareer,lineup,readiness} from '../src/state/career.js';
import {quote,negotiate,terminate} from '../src/systems/contracts.js';
import {cash,commitments,transaction} from '../src/systems/finance.js';
import {enterWeekend,startSession,tick,command,finishTimedSession,makeGrid,factors,redFlag,currentCircuit} from '../src/simulation/engine.js';
import {settleRace,advance,nextSeason,develop} from '../src/systems/season.js';
import {encode,decode,save,load} from '../src/services/save.js';
import {pointAt} from '../src/race/track.js';
import {CIRCUITS} from '../data/circuits.js';
export function prepared(seed='test',category='inter'){const s=createCareer({seed,category});for(const [kind,id] of [['rider','r0'],['rider','r1'],['staff','s0'],['staff','s1'],['supplier','aurora'],['sponsor','orbit'],['sponsor','senda']])assert.ok(negotiate(s,{kind,id,value:quote(s,kind,id)}).accepted);return s;}
export function run(s,kind){startSession(s,kind);if(kind!=='race')for(const r of lineup(s))command(s,r.id,'out');let ticks=0;while(s.session.state!=='POST_SESSION'){tick(s);if(++ticks>50000)throw Error('Sessão não termina');}return s.session;}
export function event(s){enterWeekend(s);run(s,'practice');finishTimedSession(s);run(s,'qualifying');finishTimedSession(s);s.phase='race';run(s,'race');settleRace(s);advance(s);}
test('primeira contratação, contraproposta e ledger reconciliado',()=>{const s=createCareer({seed:'contract'});const before=cash(s),q=quote(s,'rider','r0');assert.equal(negotiate(s,{kind:'rider',id:'r0',value:1}).accepted,false);assert.equal(cash(s),before);assert.ok(negotiate(s,{kind:'rider',id:'r0',value:q}).accepted);assert.equal(cash(s),before-Math.round(q*.08));assert.equal(commitments(s),q*10);assert.throws(()=>negotiate(s,{kind:'rider',id:'r0',value:q}));terminate(s,s.contracts.at(-1).id);assert.equal(lineup(s).length,0);});
test('temporada inteira, patrocinadores, P&D, mercado IA e renovação',()=>{const s=prepared('season');develop(s,'reliability');for(let i=0;i<10;i++){assert.equal(s.round,i);event(s);assert.ok(s.ledger.every(t=>Number.isFinite(t.amount)));}assert.equal(s.phase,'seasonEnd');assert.equal(s.results.length,10);assert.equal(s.history.length,1);assert.ok(s.ledger.some(t=>t.category==='sponsor'));assert.ok(s.news.some(n=>n.title==='Movimento no mercado'));assert.ok(s.projects[0].status!=='ACTIVE');assert.ok(cash(s)>0);nextSeason(s);assert.equal(s.season,2);assert.equal(s.round,0);assert.ok(readiness(s).length);for(const t of s.teams)assert.equal(lineup(s,t.id).length,2);});
test('mesma seed reproduz a temporada',()=>{const a=prepared('same'),b=prepared('same');event(a);event(b);assert.deepEqual(a,b);});
test('save e retomada no meio da corrida preservam resultado',()=>{const a=prepared('resume');enterWeekend(a);a.phase='race';startSession(a,'race');for(let i=0;i<345;i++)tick(a);const b=decode(encode(a));for(const s of [a,b])while(s.session.state!=='POST_SESSION')tick(s);assert.deepEqual(a.session,b.session);});
test('backup válido recupera slot corrompido',()=>{const data=new Map(),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};const s=prepared();save(s,'auto',storage);s.team.name='Outra';save(s,'auto',storage);storage.setItem('mrm-v3-auto','bad json');const r=load('auto',storage);assert.ok(r.recovered);assert.equal(r.state.team.name,'Valença Racing');});
test('pneu gasto e acerto distante aumentam o tempo; chuva pune slick',()=>{const s=prepared();enterWeekend(s);startSession(s,'practice');const q=s.session,e=q.entries[0],c=currentCircuit(s),seg=c.segments[0];e.setup=[...c.setup];e.wear=0;const fresh=factors(e,c,q,seg);e.wear=95;assert.ok(factors(e,c,q,seg).tyre>fresh.tyre);e.setup=[0,0,0];assert.ok(factors(e,c,q,seg).setup>fresh.setup);q.weather.wet=.9;e.tyre='soft';const dry=factors(e,c,q,seg).weather;e.tyre='wet';assert.ok(factors(e,c,q,seg).weather<dry);});
test('grid aplica penalidade e mapa fecha seu traçado',()=>{const g=makeGrid([{riderId:'a'},{riderId:'b'},{riderId:'c'}],[{riderId:'a',places:2}]);assert.equal(g[0].riderId,'b');assert.deepEqual(g.map(e=>e.gridPosition),[1,2,3]);for(const c of CIRCUITS){assert.ok(Math.abs(c.segments.reduce((a,x)=>a+x.weight,0)-1)<1e-10);assert.deepEqual(pointAt(c,0),pointAt(c,1));}});
test('bandeira vermelha para os pilotos; classificação termina por relógio',()=>{const s=prepared();enterWeekend(s);startSession(s,'practice');command(s,'r0','out');tick(s);const p=s.session.entries[0].progress;redFlag(s.session);tick(s);assert.equal(s.session.entries[0].progress,p);while(s.session.state!=='POST_SESSION')tick(s);assert.ok(s.session.elapsed>=s.session.duration);});
test('não permite iniciar sem elenco e dados ruins não substituem save',()=>{const s=createCareer();assert.throws(()=>enterWeekend(s));assert.throws(()=>decode('{"schemaVersion":999}'));assert.throws(()=>transaction(s,NaN,'bad','bad'));});
