import {FACILITIES,COMPONENTS,ADVANCED_PROJECTS,MEDIA_ACTIONS} from '../../data/part2.js';
import {ROLE_NAMES} from '../../data/config.js';
import {activeContracts,lineup} from '../state/career.js';
import {p2,facilityLevel,facilityCost,valuation} from '../systems/part2.js';
import {money,esc} from './text.js';

const button=(label,action,attrs='',cls='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const badge=text=>`<span class="badge">${esc(text)}</span>`;
const heading=(kicker,title,copy)=>`<header class="page-title"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${copy}</p></div></header>`;
const meter=(label,value)=>`<div class="metric-line"><span>${esc(label)}</span><b>${Math.round(value)}%</b><progress value="${value}" max="100"></progress></div>`;
const disabled=(condition)=>condition?'disabled aria-disabled="true"':'';

export function operations(s,asset){
 const state=p2(s),locked=s.phase!=='management',activeProject=state.projects.find(x=>x.status==='ACTIVE');
 const shipmentRows=state.shipments.filter(x=>x.status==='IN_TRANSIT').map(x=>{const item=COMPONENTS.find(c=>c.id===x.componentId);return `<div class="ops-row"><div><b>${esc(item.name)}</b><small>${x.quantity} unidade(s)</small></div>${badge(x.remaining+' etapa(s)')}</div>`;}).join('');
 const contracted=new Set(activeContracts(s,'staff').map(c=>c.entityId));
 return `${heading('CENTRO DE OPERAÇÕES','Sede, estoque e P&D','Amplie a estrutura, controle peças e conduza projetos técnicos por etapas.')}
 <div class="cards three facility-grid">${FACILITIES.map(f=>{const level=facilityLevel(s,f.id),max=level>=f.max;return `<article class="panel facility-card" style="--facility:url('${asset(f.art)}')"><div class="facility-photo"></div><span class="eyebrow">NÍVEL ${level} / ${f.max}</span><h2>${esc(f.name)}</h2><p>${esc(f.effect)}</p>${meter('Capacidade',level/f.max*100)}${button(max?'Nível máximo':'Ampliar · '+money(facilityCost(s,f.id)),'facility-upgrade',`data-id="${f.id}" ${disabled(locked||max)}`,'wide')}</article>`;}).join('')}</div>
 <div class="columns section-label"><section class="panel"><div class="panel-heading"><h2>Estoque de corrida</h2><span>LOGÍSTICA NÍVEL ${facilityLevel(s,'logistics')}</span></div>${COMPONENTS.map(c=>`<div class="ops-row"><div><b>${esc(c.name)}</b><small>Custo unitário ${money(c.cost)}</small></div><strong class="${state.inventory[c.id]===0?'negative':''}">${state.inventory[c.id]}</strong>${button('Pedir 1','component-order',`data-id="${c.id}" ${disabled(locked)}`,'compact')}</div>`).join('')}<h3 class="section-label">Em trânsito</h3>${shipmentRows||'<p class="muted">Nenhuma entrega pendente.</p>'}</section>
 <section class="panel"><div class="panel-heading"><h2>Projeto em validação</h2><span>${activeProject?'EM CURSO':'CAPACIDADE LIVRE'}</span></div>${activeProject?`<h3>${esc(activeProject.name)}</h3><p>Etapa: ${esc(ADVANCED_PROJECTS.find(x=>x.id===activeProject.specId)?.stages[activeProject.stage]||'Conclusão')}</p>${meter('Progresso',activeProject.progress)}<p class="muted">O ganho e eventuais efeitos colaterais aparecem após a validação.</p>`:'<p class="muted">Escolha um projeto no dossiê técnico abaixo.</p>'}</section></div>
 <h2 class="section-label">Dossiês de desenvolvimento avançado</h2><div class="cards three">${ADVANCED_PROJECTS.map(x=>`<article class="panel tech-card"><span class="eyebrow">${esc(ROLE_NAMES.engineer)} · ${x.stages.length} FASES</span><h2>${esc(x.name)}</h2><p>Foco: ${esc(x.attribute)} · risco técnico ${Math.round(x.risk*100)}% · instalação: ${esc(FACILITIES.find(f=>f.id===x.facility).name)}</p><h3>${money(x.cost)}<small> base</small></h3>${button('Iniciar dossiê','advanced-start',`data-id="${x.id}" ${disabled(locked||!!activeProject)}`,'wide')}</article>`).join('')}</div>
 <h2 class="section-label">Carga de trabalho</h2><div class="cards three">${s.staff.filter(x=>contracted.has(x.id)).map(member=>{const st=state.staffStates[member.id];return `<article class="panel"><span class="eyebrow">${esc(ROLE_NAMES[member.role]||member.role)}</span><h3>${esc(member.name)}</h3>${meter('Moral',st.morale)}${meter('Fadiga',st.fatigue)}${meter('Desenvolvimento',st.development)}<div class="actions">${button('Recuperar','staff-action',`data-id="${member.id}" data-mode="rest" ${disabled(locked)}`,'compact')}${button('Treinar','staff-action',`data-id="${member.id}" data-mode="train" ${disabled(locked)}`,'compact')}</div></article>`;}).join('')||'<section class="panel"><p class="muted">Contrate profissionais para acompanhar carga e evolução.</p></section>'}</div>`;
}

function portraitSprite(person,asset){const cols=person.portraitCols||4,rows=person.portraitRows||2,index=person.portraitIndex||0,x=cols>1?(index%cols)/(cols-1)*100:0,y=rows>1?Math.floor(index/cols)/(rows-1)*100:0;return `<div class="portrait portrait-sprite" role="img" aria-label="${esc(person.name)}" style="--portrait:url('${esc(asset(person.portraitSheet))}');--portrait-size-x:${cols*100}%;--portrait-size-y:${rows*100}%;--portrait-x:${x}%;--portrait-y:${y}%"></div>`;}

export function academy(s,asset=()=> ''){
 const state=p2(s),locked=s.phase!=='management',signed=new Set(state.academy.signed),full=lineup(s).length>=2;
 return `${heading('PROGRAMA DE TALENTOS','Scouting e academia','Relatórios reduzem incerteza. Uma academia própria transforma promessa em opção real para o elenco.')}
 <div class="operation-banner"><div><span class="eyebrow">ESTRUTURA ATUAL</span><h2>Academia nível ${facilityLevel(s,'academy')}</h2><p>${state.academy.signed.length} talento(s) em formação · investimento acumulado ${money(state.academy.budget)}</p></div>${facilityLevel(s,'academy')===0?button('Construir academia','facility-upgrade',`data-id="academy" ${disabled(locked)}`,'primary'):badge('Programa ativo')}</div>
 <div class="people-grid academy-grid">${state.academy.prospects.map(y=>{const report=state.scouting.reports[y.id],isSigned=signed.has(y.id);return `<article class="person-card academy-card ${isSigned?'owned':''}"><div class="person-visual academy-visual">${portraitSprite(y,asset)}<div class="academy-number">${esc(y.nationality)}<strong>${Math.round(y.level)}</strong><small>NÍVEL ESTIMADO</small></div></div><div class="person-body"><span class="eyebrow">${y.age} ANOS · ${esc(y.style)}</span><h2>${esc(y.name)}</h2>${report?`<p>Ritmo ${report.level[0]}–${report.level[1]} · potencial ${report.potential[0]}–${report.potential[1]}</p>${badge(report.confidence+'% de confiança')}`:'<p class="muted">Dados técnicos ainda não verificados.</p>'}<div class="actions">${button(report?'Atualizar relatório':'Observar','scout',`data-id="${y.id}" ${disabled(locked)}`,'compact')}${isSigned?button(full?'Elenco principal completo':'Promover','academy-promote',`data-id="${y.id}" ${disabled(locked||full)}`,'primary compact'):button('Assinar bolsa · '+money(y.cost),'academy-sign',`data-id="${y.id}" ${disabled(locked||facilityLevel(s,'academy')<1)}`,'compact')}</div>${isSigned?'<p class="positive">Em formação; evolui após cada etapa.</p>':''}</div></article>`;}).join('')}</div>`;
}

export function mediaCenter(s,asset){
 const state=p2(s),locked=!['management','result'].includes(s.phase);
 return `${heading('MARCA GLOBAL','Mídia e comunidade','Campanhas ampliam fãs, reputação e valor comercial; ações maiores trazem mais risco.')}
 <div class="media-hero" style="--scene:url('${asset('art-022')}')"><div><span class="eyebrow">AUDIÊNCIA PRÓPRIA</span><h2>${state.fans.toLocaleString('pt-BR')} fãs</h2><p>Engajamento ${Math.round(state.engagement)}% · valor de mídia ${Math.round(state.mediaValue)}/100 · marca ${Math.round(state.brandReputation)}/100</p></div></div>
 <div class="cards two section-label">${MEDIA_ACTIONS.map(a=>`<article class="panel campaign-card"><span class="eyebrow">ALCANCE PROJETADO +${a.fans.toLocaleString('pt-BR')}</span><h2>${esc(a.name)}</h2><p>${esc(a.description)}</p><div class="campaign-meta">${badge('Marca +'+a.brand)}${badge(a.risk?'Risco '+Math.round(a.risk*100)+'%':'Sem risco de crise')}</div><h3>${money(a.cost)}<small> base</small></h3>${button('Publicar campanha','media-action',`data-id="${a.id}" ${disabled(locked)}`,'primary wide')}</article>`).join('')}</div>
 <section class="panel section-label"><h2>Histórico editorial</h2>${state.mediaHistory.length?state.mediaHistory.slice(0,12).map(x=>{const a=MEDIA_ACTIONS.find(v=>v.id===x.action);return `<div class="ops-row"><div><b>${esc(a?.name||x.action)}</b><small>Ano ${x.season} · etapa ${x.round+1}</small></div><span class="${x.crisis?'negative':'positive'}">${x.fans>=0?'+':''}${x.fans.toLocaleString('pt-BR')} fãs</span>${badge(x.crisis?'CRISE':'PUBLICADA')}</div>`;}).join(''):'<p class="muted">A equipe ainda não publicou campanhas.</p>'}</section>`;
}

export function worldCenter(s,asset){
 const state=p2(s),openOffers=state.investorOffers.filter(x=>x.status==='OPEN'),openEvents=state.worldEvents.filter(x=>x.status==='OPEN');
 const injuries=state.injuries.filter(x=>state.riderStates[x.riderId]?.injuryRounds>0);
 return `${heading('SALA DA DIRETORIA','Mundo, governança e relações','Acompanhe investidores, decisões esportivas, rivalidades e eventos que mudam sua carreira.')}
 <div class="world-hero" style="--scene:url('${asset('art-084')}')"><div><span class="eyebrow">VALOR ESTIMADO DA EQUIPE</span><h2>${money(valuation(s))}</h2><p>${state.equityOwned}% sob seu controle · pressão do investidor ${Math.round(state.investorPressure)}/100</p></div>${openOffers.length?'':button('Buscar investidor','investor-create',disabled(s.phase!=='management'),'primary')}</div>
 <div class="columns section-label"><section class="panel"><div class="panel-heading"><h2>Decisões pendentes</h2><span>${openEvents.length}</span></div>${openEvents.length?openEvents.map(ev=>`<article class="decision-card"><span class="eyebrow">AÇÃO DA DIRETORIA</span><h3>${esc(ev.title)}</h3><p>${esc(ev.body)}</p><div class="actions">${ev.choices.map(c=>button(esc(c[1]),'world-event',`data-id="${ev.id}" data-choice="${c[0]}"`,'compact')).join('')}</div></article>`).join(''):'<p class="muted">Nenhuma decisão urgente.</p>'}</section>
 <section class="panel"><div class="panel-heading"><h2>Investidores</h2><span>${state.equityOwned}% PRÓPRIO</span></div>${openOffers.length?openOffers.map(o=>`<article class="decision-card"><h3>${money(o.amount)} por ${o.equity}%</h3><p>Pressão de governança +${o.pressure}. Expira após a etapa ${Math.min(10,o.expiresRound+1)}.</p><div class="actions">${button('Recusar','investor-decision',`data-id="${o.id}" data-accept="false"`,'compact')}${button('Aceitar aporte','investor-decision',`data-id="${o.id}" data-accept="true"`,'primary compact')}</div></article>`).join(''):'<p class="muted">Nenhuma oferta aberta. A avaliação usa caixa, instalações, desempenho e alcance da marca.</p>'}</section></div>
 <div class="cards three section-label"><section class="panel"><h2>Departamento médico</h2>${injuries.length?injuries.map(i=>{const r=s.riders.find(x=>x.id===i.riderId),rs=state.riderStates[i.riderId];return `<div class="ops-row"><div><b>${esc(r.name)}</b><small>Limitação técnica ${Math.round(rs.injurySeverity)}%</small></div>${badge(rs.injuryRounds+' etapa(s)')}</div>`;}).join(''):'<p class="positive">Elenco disponível.</p>'}</section>
 <section class="panel"><h2>Rivalidades internas</h2>${state.rivalries.length?state.rivalries.map(rv=>`<div class="ops-row"><div><b>${rv.riderIds.map(id=>esc(s.riders.find(r=>r.id===id)?.short||id)).join(' × ')}</b><small>${esc(rv.reason)}</small></div>${badge('Intensidade '+rv.intensity)}</div>`).join(''):'<p class="muted">Sem rivalidades declaradas.</p>'}</section>
 <section class="panel"><h2>Regulamento atual</h2><h3>${esc(state.regulation.name)}</h3><p>Parc fermé: ${state.regulation.parcFerme?'sim':'não'}<br>Motores: ${state.regulation.engineAllocation}<br>Jogos de pneus: ${state.regulation.tyreSets}</p><p class="muted">Comissários podem aplicar penalidades na classificação.</p></section></div>
 <section class="panel section-label"><h2>Livro da operação</h2>${state.history.length?`<div class="table-scroll"><table><thead><tr><th>Ano / etapa</th><th>Avaliação</th><th>Fãs</th><th>Marca</th><th>Fadiga</th></tr></thead><tbody>${state.history.slice().reverse().map(h=>`<tr><td>${h.season} / ${h.round+1}</td><td>${money(h.valuation)}</td><td>${h.fans.toLocaleString('pt-BR')}</td><td>${h.brand}</td><td>${h.staffFatigue}%</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">O primeiro registro será criado após a corrida.</p>'}</section>`;
}
