import {BALANCE,SPONSORS,MANUFACTURERS} from '../../data/config.js';
import {spend,category,philosophy} from './finance.js';
import {activeContracts,news,staffSkill} from '../state/career.js';
export function quote(s,kind,id){const entity=kind==='rider'?s.riders.find(x=>x.id===id):kind==='staff'?s.staff.find(x=>x.id===id):kind==='sponsor'?SPONSORS.find(x=>x.id===id):MANUFACTURERS.find(x=>x.id===id);if(!entity)throw Error('Parceiro inexistente.');const value=kind==='sponsor'?entity.perRound*philosophy(s).sponsor*(1+(staffSkill(s,'commercial')-40)/400):entity.salary||entity.fee;return Math.round(value*category(s).cost);}
export function negotiate(s,{kind,id,value,duration=1,teamId='player'}){if(s.phase!=='management')throw Error('Conclua a etapa antes de negociar.');if(!['rider','staff','supplier','sponsor'].includes(kind)||!Number.isFinite(value)||value<=0||![1,2,3].includes(duration))throw Error('Proposta inválida.');const expected=quote(s,kind,id);const occupied=s.contracts.find(c=>c.entityId===id&&c.kind===kind&&c.status==='ACTIVE'&&(kind==='rider'||kind==='staff'||c.teamId===teamId));if(occupied)throw Error('Já existe contrato ativo para esta pessoa ou parceiro.');if(kind==='rider'&&activeContracts(s,kind,teamId).length>=2)throw Error('A equipe já tem dois pilotos.');if(kind==='staff'){const role=s.staff.find(x=>x.id===id).role;if(activeContracts(s,'staff',teamId).some(c=>s.staff.find(x=>x.id===c.entityId).role===role))throw Error('A função já está preenchida.');}if(kind==='supplier'&&s.team.manufacturer)throw Error('Encerre o fornecimento atual primeiro.');if(kind==='sponsor'&&s.team.reputation<SPONSORS.find(x=>x.id===id).reputation)throw Error('A reputação ainda não atende à marca.');
 const key=teamId+':'+kind+':'+id;const memory=s.negotiations[key]||{attempts:0,status:'DRAFT'};memory.attempts++;const threshold=expected*(kind==='sponsor'?1.06: .94)+ (kind==='sponsor'?-1:1)*expected*Math.min(memory.attempts-1,3)*.015;const accepted=kind==='sponsor'?value<=threshold:value>=threshold;s.negotiations[key]={...memory,status:accepted?'ACCEPTED':'COUNTERED',offer:value,counter:Math.round(expected),duration};if(!accepted)return {accepted:false,counter:expected};
 if(kind!=='sponsor')spend(s,value*BALANCE.signingFee,'signing','Luvas de contratação',teamId);
 const c={id:'c'+s.contracts.length,kind,entityId:id,teamId,value:Math.round(value),startSeason:s.season,endSeason:s.season+duration-1,status:'ACTIVE',bonus:kind==='rider'?4000*category(s).cost:0,termination:BALANCE.termination};s.contracts.push(c);if(kind==='supplier')s.team.manufacturer=id;news(s,'Contrato assinado',`${kind==='rider'?s.riders.find(x=>x.id===id).name:kind==='staff'?s.staff.find(x=>x.id===id).name:id} assinou por ${duration} temporada(s).`);return {accepted:true,contract:c};
}
export function terminate(s,id){if(s.phase!=='management')throw Error('Conclua a etapa antes de rescindir.');const c=s.contracts.find(c=>c.id===id&&c.teamId==='player'&&c.status==='ACTIVE');if(!c)throw Error('Contrato não encontrado.');const remaining=(c.endSeason-s.season)*s.calendar.length+s.calendar.length-s.round;spend(s,c.value*remaining*BALANCE.termination,'termination','Rescisão contratual');c.status='TERMINATED';if(c.kind==='supplier')s.team.manufacturer=null;news(s,'Contrato encerrado','Multa registrada no caixa.');}
