import {FACILITIES,COMPONENTS,ADVANCED_PROJECTS,MEDIA_ACTIONS,EVENT_TEMPLATES} from '../../data/part2.js';
import {random,clamp} from '../core/random.js';
import {activeContracts,news,staffSkill,lineup} from '../state/career.js';
import {ensurePart2} from '../state/part2.js';
import {cash,spend,transaction,category} from './finance.js';

export const p2=s=>ensurePart2(s).part2;
export const facilityLevel=(s,id)=>p2(s).facilities[id]||0;
export const facilityCost=(s,id)=>{const f=FACILITIES.find(x=>x.id===id);return Math.round(f.baseCost*Math.pow(1.65,facilityLevel(s,id))*category(s).cost);};
export function upgradeFacility(s,id){if(s.phase!=='management')throw Error('Obras só podem começar entre etapas.');const f=FACILITIES.find(x=>x.id===id);if(!f)throw Error('Instalação inválida.');const level=facilityLevel(s,id);if(level>=f.max)throw Error('Esta instalação já está no nível máximo.');const cost=facilityCost(s,id);spend(s,cost,'facilities','Ampliação: '+f.name);p2(s).facilities[id]=level+1;news(s,'Sede ampliada',`${f.name} agora está no nível ${level+1}. Custos fixos e capacidade foram atualizados.`);return level+1;}

export function orderComponent(s,id,quantity=1){if(s.phase!=='management')throw Error('Pedidos precisam ser fechados antes da viagem.');const item=COMPONENTS.find(x=>x.id===id);quantity=Math.floor(quantity);if(!item||quantity<1||quantity>20)throw Error('Pedido inválido.');const cost=item.cost*quantity*category(s).cost;spend(s,cost,'parts',`Pedido: ${quantity} × ${item.name}`);const reduction=Math.min(item.lead-1,Math.floor(facilityLevel(s,'logistics')/2)+Math.floor((staffSkill(s,'logistics')-40)/25));p2(s).shipments.push({id:'sh'+Date.now()+p2(s).shipments.length,componentId:id,quantity,cost,remaining:Math.max(1,item.lead-reduction),status:'IN_TRANSIT'});news(s,'Peças em trânsito',`${quantity} × ${item.name}; chegada prevista em ${Math.max(1,item.lead-reduction)} etapa(s).`);}

export function startAdvancedProject(s,id){if(s.phase!=='management')throw Error('Projetos só começam entre etapas.');const spec=ADVANCED_PROJECTS.find(x=>x.id===id);if(!spec)throw Error('Projeto inválido.');if(p2(s).projects.some(x=>x.status==='ACTIVE'))throw Error('A capacidade atual permite um projeto avançado por vez.');if(staffSkill(s,'engineer')===40)throw Error('Contrate engenharia antes de iniciar o projeto.');const required=facilityLevel(s,spec.facility);if(required<1)throw Error('A instalação técnica necessária ainda não existe.');const cost=Math.round(spec.cost*category(s).cost*(1-Math.min(required-1,3)*.04));spend(s,cost,'development','Projeto avançado: '+spec.name);p2(s).projects.push({id:'p2-'+p2(s).projects.length,specId:id,name:spec.name,attribute:spec.attribute,sideEffect:spec.sideEffect,cost,stage:0,progress:0,status:'ACTIVE',gain:null,sideEffectValue:0,staffId:activeContracts(s,'staff').find(c=>s.staff.find(x=>x.id===c.entityId)?.role==='engineer')?.entityId||null});news(s,'Projeto aprovado',`${spec.name} entrou em ${spec.stages[0].toLowerCase()}. Risco, prazo e efeito colateral serão revelados na validação.`);}

export function staffAction(s,id,action){if(s.phase!=='management')throw Error('Gerencie o staff entre etapas.');const member=s.staff.find(x=>x.id===id),st=p2(s).staffStates[id];if(!member||!st)throw Error('Profissional inválido.');if(!activeContracts(s,'staff').some(c=>c.entityId===id))throw Error('Este profissional não pertence à equipe.');if(action==='rest'){st.fatigue=clamp(st.fatigue-28,0,100);st.morale=clamp(st.morale+5,0,100);transaction(s,-Math.round(member.salary*.3),'operations','Folga e recuperação: '+member.name);}else if(action==='train'){spend(s,18000,'training','Formação profissional: '+member.name);st.development+=25;st.fatigue=clamp(st.fatigue+8,0,100);if(st.development>=100){st.development-=100;member.skill=clamp(member.skill+1,0,95);for(const k in member.attributes)member.attributes[k]=clamp(member.attributes[k]+1,0,99);news(s,'Evolução de staff',`${member.name} concluiu uma especialização e elevou sua competência.`);}}else throw Error('Ação de staff inválida.');}

export function scoutProspect(s,id){if(s.phase!=='management')throw Error('O scouting trabalha entre etapas.');const prospect=p2(s).academy.prospects.find(x=>x.id===id);if(!prospect)throw Error('Talento não encontrado.');spend(s,9000,'scouting','Relatório de scouting: '+prospect.name);const scout=staffSkill(s,'scout'),uncertainty=Math.max(2,Math.round((100-scout)/8));p2(s).scouting.reports[id]={id,confidence:clamp(45+scout/2,45,95),level:[Math.max(40,prospect.level-uncertainty),Math.min(99,prospect.level+uncertainty)],potential:[Math.max(50,prospect.potential-uncertainty),Math.min(99,prospect.potential+uncertainty)],strength:Object.entries(prospect.attributes).sort((a,b)=>b[1]-a[1])[0][0],risk:prospect.potential-prospect.level>28?'Desenvolvimento longo':'Moderado',season:s.season,round:s.round};news(s,'Relatório entregue',`A observação de ${prospect.name} atingiu ${Math.round(45+scout/2)}% de confiança.`);}

export function signAcademy(s,id){if(s.phase!=='management')throw Error('Assine talentos entre etapas.');const academy=p2(s).academy,prospect=academy.prospects.find(x=>x.id===id);if(!prospect)throw Error('Talento não encontrado.');if(academy.signed.includes(id))throw Error('Este piloto já está na academia.');if(facilityLevel(s,'academy')<1)throw Error('Construa a academia antes de contratar jovens.');spend(s,prospect.cost,'academy','Bolsa de formação: '+prospect.name);academy.signed.push(id);academy.budget+=prospect.cost;news(s,'Novo talento na academia',`${prospect.name} iniciou o programa de formação da equipe.`);}

export function promoteProspect(s,id){if(s.phase!=='management')throw Error('Promova pilotos entre etapas.');const academy=p2(s).academy,prospect=academy.prospects.find(x=>x.id===id);if(!prospect||!academy.signed.includes(id))throw Error('O piloto não pertence à academia.');if(activeContracts(s,'rider').length>=2)throw Error('Abra uma vaga no elenco principal antes da promoção.');const rider={...structuredClone(prospect),short:prospect.name.split(' ').at(-1),number:70+Number(id.slice(1)),agent:'Programa de jovens '+s.team.short,biography:'Formado na academia da equipe, chega ao elenco principal após acompanhamento técnico.',salary:12000+prospect.level*350,marketability:45,personality:'Promessa da academia'};s.riders.push(rider);p2(s).riderStates[id]={confidence:66,pressure:38,frustration:5,motivation:88,teamTrust:82,injuryRounds:0,injurySeverity:0};s.contracts.push({id:'c'+s.contracts.length,kind:'rider',entityId:id,teamId:'player',value:rider.salary,startSeason:s.season,endSeason:s.season+1,status:'ACTIVE',bonus:2500,termination:.25});academy.signed=academy.signed.filter(x=>x!==id);academy.prospects=academy.prospects.filter(x=>x.id!==id);news(s,'Promoção ao elenco principal',`${rider.name} assinou por duas temporadas após subir da academia.`);return rider;}

export function runMediaAction(s,id){const action=MEDIA_ACTIONS.find(x=>x.id===id);if(!action)throw Error('Campanha inválida.');if(s.phase!=='management'&&s.phase!=='result')throw Error('A campanha não pode ser iniciada durante uma sessão.');const cost=Math.round(action.cost*category(s).cost);spend(s,cost,'marketing','Campanha: '+action.name);const studio=facilityLevel(s,'mediaStudio'),media=staffSkill(s,'media');let multiplier=1+studio*.08+(media-40)*.006;const crisis=random(s)<action.risk*(1-media/200);let fans=Math.round(action.fans*multiplier*(crisis?-.35:1)),brand=crisis?-2:Math.round(action.brand*multiplier);p2(s).fans=Math.max(0,p2(s).fans+fans);p2(s).brandReputation=clamp(p2(s).brandReputation+brand,0,100);p2(s).engagement=clamp(p2(s).engagement+(crisis?-4:3),0,100);p2(s).mediaValue=clamp(p2(s).mediaValue+(crisis?-2:2),0,100);p2(s).mediaHistory.unshift({season:s.season,round:s.round,action:id,cost,fans,brand,crisis});news(s,crisis?'Campanha sob críticas':'Campanha publicada',crisis?`${action.name} gerou reação negativa; a equipe perdeu ${Math.abs(fans)} seguidores.`:`${action.name} alcançou novos públicos e adicionou ${fans} fãs.`);}

export function valuation(s){const assets=Object.values(p2(s).facilities).reduce((a,l)=>a+l*260000,0);const sport=(s.teamStandings.player||0)*18000;return Math.max(800000,Math.round(cash(s)+assets+p2(s).fans*14+s.team.reputation*24000+p2(s).brandReputation*16000+sport-s.debt));}
export function createInvestorOffer(s){if(s.phase!=='management')throw Error('Negocie com investidores entre etapas.');if(p2(s).investorOffers.some(x=>x.status==='OPEN'))throw Error('Já existe uma proposta em análise.');const value=valuation(s),equity=clamp(8+Math.round(random(s)*14),8,22),amount=Math.round(value*(equity/100)*(1+(random(s)-.5)*.2));const offer={id:'inv-'+s.season+'-'+s.round,equity,amount,pressure:Math.round(12+equity*.8),status:'OPEN',expiresRound:s.round+2};p2(s).investorOffers.unshift(offer);news(s,'Proposta de investimento',`Um fundo oferece capital por ${equity}% da equipe. A proposta expira em duas etapas.`);return offer;}
export function decideInvestor(s,id,accept){if(s.phase!=='management')throw Error('Decida sobre investidores entre etapas.');const offer=p2(s).investorOffers.find(x=>x.id===id&&x.status==='OPEN');if(!offer)throw Error('Proposta não está disponível.');offer.status=accept?'ACCEPTED':'REJECTED';if(accept){p2(s).equityOwned=clamp(p2(s).equityOwned-offer.equity,0,100);p2(s).investorPressure=clamp(p2(s).investorPressure+offer.pressure,0,100);transaction(s,offer.amount,'investment','Entrada de investidor');news(s,'Novo investidor',`${offer.amount.toLocaleString('pt-BR')} euros entraram no caixa; sua participação passou a ${p2(s).equityOwned}%.`);}else news(s,'Proposta recusada','A equipe preservou sua participação e autonomia.');}

export function qualifyingPenalties(s,result){const regulation=p2(s).regulation;if(random(s)>=regulation.penaltyChance)return [];const candidates=result.filter(x=>x.best!==null),target=candidates[Math.floor(random(s)*candidates.length)];if(!target)return [];const places=random(s)<.25?3:1,decision={id:'sd-'+p2(s).sportsDecisions.length,type:'GRID_PENALTY',riderId:target.riderId,teamId:target.teamId,session:'qualifying',reason:random(s)<.5?'Impedimento em volta rápida':'Uso de componente fora da alocação',places,appeal:false,season:s.season,round:s.round};p2(s).sportsDecisions.unshift(decision);news(s,'Decisão dos comissários',`${s.riders.find(r=>r.id===target.riderId).name} perde ${places} posição(ões) no grid: ${decision.reason.toLowerCase()}.`);return [decision];}

export function resolveWorldEvent(s,id,choice){if(!['management','result','seasonEnd'].includes(s.phase))throw Error('Resolva decisões fora das sessões de pista.');const event=p2(s).worldEvents.find(x=>x.id===id&&x.status==='OPEN');if(!event)throw Error('Este evento já foi resolvido.');const valid=event.choices.some(x=>x[0]===choice);if(!valid)throw Error('Resposta inválida.');event.status='RESOLVED';event.choice=choice;const staff=Object.values(p2(s).staffStates);if(event.templateId==='staffFatigue'){if(choice==='rest'){transaction(s,-32000,'operations','Programa de recuperação do staff');staff.forEach(x=>{x.fatigue=clamp(x.fatigue-22,0,100);x.morale=clamp(x.morale+4,0,100);});}else staff.forEach(x=>{x.fatigue=clamp(x.fatigue+10,0,100);x.morale=clamp(x.morale-5,0,100);});}
 if(event.templateId==='sponsorActivation'){if(choice==='attend'){transaction(s,-24000,'marketing','Ativação comercial');p2(s).fans+=8500;p2(s).brandReputation=clamp(p2(s).brandReputation+3,0,100);}else p2(s).brandReputation=clamp(p2(s).brandReputation-2,0,100);}
 if(event.templateId==='technicalAlert'){if(choice==='replace'){transaction(s,-62000,'parts','Lote emergencial de componentes');p2(s).inventory.fairing+=2;p2(s).inventory.brakes+=1;}else{s.team.morale=clamp(s.team.morale-2,0,100);p2(s).inventory.electronics=Math.max(0,p2(s).inventory.electronics-1);}}
 if(event.templateId==='rivalApproach'){if(choice==='raise'){transaction(s,-28000,'bonus','Bônus de retenção');staff.forEach(x=>x.loyalty=clamp(x.loyalty+7,0,100));}else staff.forEach(x=>x.loyalty=clamp(x.loyalty-3,0,100));}
 if(event.templateId==='mediaQuestion'){if(choice==='honest'){p2(s).brandReputation=clamp(p2(s).brandReputation+2,0,100);s.team.morale=clamp(s.team.morale-1,0,100);}else{p2(s).fans+=4200;p2(s).investorPressure=clamp(p2(s).investorPressure+4,0,100);}}
 news(s,'Decisão registrada',`${event.title}: ${event.choices.find(x=>x[0]===choice)[1]}. A consequência já foi aplicada.`);}

export function processPart2Round(s,result){const state=p2(s),player=result.entries.filter(e=>e.teamId==='player');
 for(const shipment of state.shipments.filter(x=>x.status==='IN_TRANSIT')){shipment.remaining--;if(shipment.remaining<=0){shipment.status='DELIVERED';state.inventory[shipment.componentId]+=shipment.quantity;const item=COMPONENTS.find(x=>x.id===shipment.componentId);news(s,'Entrega recebida',`${shipment.quantity} × ${item.name} entraram no estoque.`);}}
 const incidents=result.incidents.filter(i=>player.some(e=>e.riderId===i.riderId));state.inventory.fairing=Math.max(0,state.inventory.fairing-incidents.length);state.inventory.brakes=Math.max(0,state.inventory.brakes-Math.ceil(incidents.length/2));state.inventory.engine=Math.max(0,state.inventory.engine-player.filter(e=>e.status==='RETIRED').length);if(Object.entries(state.inventory).some(([,n])=>n===0))news(s,'Estoque crítico','Um componente chegou a zero. Faça um pedido antes da próxima viagem.');
 for(const c of activeContracts(s,'staff')){const st=state.staffStates[c.entityId];st.fatigue=clamp(st.fatigue+5+incidents.length*2-facilityLevel(s,'performance'),0,100);st.morale=clamp(st.morale+(player.some(e=>e.position<=5)?3:-1),0,100);st.loyalty=clamp(st.loyalty+(st.satisfaction>65?1:-1),0,100);}
 for(const e of player){const rs=state.riderStates[e.riderId];rs.confidence=clamp(rs.confidence+(e.position<=5?5:e.position<=12?1:-3),0,100);rs.pressure=clamp(rs.pressure+(e.position>12?3:-2)+state.investorPressure*.015,0,100);rs.frustration=clamp(rs.frustration+(e.status==='RETIRED'?10:e.position>12?3:-2),0,100);rs.motivation=clamp(rs.motivation+(e.position<=8?3:-1),0,100);if(e.status==='RETIRED'&&random(s)<.22){const rounds=Math.max(1,Math.round(1+random(s)*3-facilityLevel(s,'performance')*.3-(staffSkill(s,'physio')-40)/100));rs.injuryRounds=rounds;rs.injuryStartRound=s.round;rs.injurySeverity=clamp(8+rounds*7,8,35);state.injuries.unshift({id:'inj-'+state.injuries.length,riderId:e.riderId,rounds,severity:rs.injurySeverity,status:'ACTIVE',season:s.season,round:s.round});news(s,'Piloto em recuperação',`${s.riders.find(r=>r.id===e.riderId).name} ficará limitado por ${rounds} etapa(s).`);}}
 for(const rs of Object.values(state.riderStates))if(rs.injuryRounds>0&&rs.injuryStartRound!==s.round){rs.injuryRounds--;if(rs.injuryRounds===0){rs.injurySeverity=0;for(const injury of state.injuries.filter(x=>x.riderId===Object.keys(state.riderStates).find(id=>state.riderStates[id]===rs)&&x.status==='ACTIVE'))injury.status='RECOVERED';}}
 if(player.length===2&&Math.abs(player[0].position-player[1].position)<=2){const ids=player.map(e=>e.riderId).sort(),existing=state.rivalries.find(x=>x.riderIds[0]===ids[0]&&x.riderIds[1]===ids[1]);if(existing){existing.intensity=clamp(existing.intensity+5,0,100);existing.lastRound=s.round;}else state.rivalries.push({id:'rv-'+state.rivalries.length,riderIds:ids,intensity:12,reason:'Disputa direta por posições',createdSeason:s.season,lastRound:s.round});}
 for(const project of state.projects.filter(x=>x.status==='ACTIVE')){const spec=ADVANCED_PROJECTS.find(x=>x.id===project.specId),skill=staffSkill(s,'engineer'),facility=facilityLevel(s,spec.facility);project.progress+=clamp(45+skill*.35+facility*8-activeContracts(s,'staff').reduce((a,c)=>a+state.staffStates[c.entityId].fatigue,0)/Math.max(1,activeContracts(s,'staff').length)*.18,25,95);if(project.progress>=100){project.progress=0;project.stage++;if(project.stage>=spec.stages.length){const failureChance=clamp(spec.risk-(skill-60)*.002-facility*.015,.03,.35),ok=random(s)>=failureChance;project.status=ok?'COMPLETE':'FAILED';if(ok){project.gain=Math.round(spec.gain[0]+random(s)*(spec.gain[1]-spec.gain[0]));s.upgrades[spec.attribute]+=project.gain;if(random(s)<spec.risk*.55){project.sideEffectValue=-1;s.upgrades[spec.sideEffect]=Math.max(-5,s.upgrades[spec.sideEffect]-1);}news(s,'Projeto validado',`${spec.name}: +${project.gain} em ${spec.attribute}${project.sideEffectValue?' e efeito colateral de -1 em '+spec.sideEffect:''}.`);}else news(s,'Projeto reprovado',`${spec.name} falhou na validação. O custo foi registrado, sem ganho técnico.`);}}}
 for(const id of state.academy.signed){const y=state.academy.prospects.find(x=>x.id===id);if(y){const gain=.4+facilityLevel(s,'academy')*.18+facilityLevel(s,'performance')*.08;y.level=Math.min(y.potential,y.level+gain);for(const k in y.attributes)y.attributes[k]=Math.min(y.potential,y.attributes[k]+gain*.6);}}
 const fixed=Object.values(state.facilities).reduce((a,l)=>a+l*5500,0);transaction(s,-fixed,'facilities','Custos fixos da sede');state.fans=Math.max(0,state.fans+player.reduce((a,e)=>a+(e.position<=3?9000:e.position<=10?2200:-300),0));state.mediaValue=clamp(state.mediaValue+(player.some(e=>e.position<=5)?2:0),0,100);
 for(const t of s.teams){const strat=state.aiStrategies[t.id]||{focus:['speed','traction','reliability'][Math.floor(random(s)*3)],development:0,aggression:random(s)};strat.development+=t.competence*.01;if(strat.development>=3){strat.development-=3;t.competence=clamp(t.competence+1,50,92);}state.aiStrategies[t.id]=strat;}
 if(state.worldEvents.filter(x=>x.status==='OPEN').length<2){const template=EVENT_TEMPLATES[Math.floor(random(s)*EVENT_TEMPLATES.length)];state.worldEvents.unshift({id:'ev-'+s.season+'-'+s.round+'-'+state.worldEvents.length,templateId:template.id,title:template.title,body:template.body,choices:structuredClone(template.choices),status:'OPEN',season:s.season,round:s.round});news(s,'Ação necessária',template.title+': uma decisão aguarda na central do mundo.');}
 if((cash(s)<900000||s.team.reputation>55)&&!state.investorOffers.some(x=>x.status==='OPEN')&&random(s)<.45)createInvestorOffer(s);
 for(const offer of state.investorOffers.filter(x=>x.status==='OPEN'&&x.expiresRound<s.round))offer.status='EXPIRED';state.history.push({season:s.season,round:s.round,valuation:valuation(s),fans:state.fans,brand:state.brandReputation,staffFatigue:Math.round(activeContracts(s,'staff').reduce((a,c)=>a+state.staffStates[c.entityId].fatigue,0)/Math.max(1,activeContracts(s,'staff').length))});
}


