import {BALANCE as B,SPONSORS} from '../../data/config.js';
import {random,clamp} from '../core/random.js';
import {activeContracts,lineup,news,staffSkill} from '../state/career.js';
import {category,philosophy,transaction,cash,spend} from './finance.js';
import {ranking,currentCircuit} from '../simulation/engine.js';
import {negotiate,quote} from './contracts.js';
export function standings(s,teams=false){const ids=teams?['player',...s.teams.map(t=>t.id)]:s.riders.map(r=>r.id);const points=teams?s.teamStandings:s.standings;return ids.map(id=>({id,points:points[id]||0,finishes:s.results.flatMap(r=>r.entries.filter(e=>(teams?e.teamId:e.riderId)===id).map(e=>e.position)).sort((a,b)=>a-b)})).sort((a,b)=>b.points-a.points||countback(a.finishes,b.finishes)||a.id.localeCompare(b.id));}
function countback(a,b){for(let p=1;p<=24;p++){const d=b.filter(x=>x===p).length-a.filter(x=>x===p).length;if(d)return d;}return 0;}
export function settleRace(s){const q=s.session;if(!q||q.kind!=='race'||q.state!=='POST_SESSION')throw Error('A corrida ainda não terminou.');const result={season:s.season,round:s.round,circuit:currentCircuit(s).id,weather:{...q.weather},incidents:[...q.incidents],entries:ranking(q).map((e,i)=>({riderId:e.riderId,teamId:e.teamId,position:i+1,time:e.finishedAt,best:e.best,status:e.status,wear:e.wear,health:e.health,grid:e.grid,points:e.status==='FINISHED'?(B.points[i]||0):0}))};
 for(const e of result.entries){s.standings[e.riderId]=(s.standings[e.riderId]||0)+e.points;s.teamStandings[e.teamId]=(s.teamStandings[e.teamId]||0)+e.points;if(e.teamId==='player'){transaction(s,(e.status==='FINISHED'?B.prizeBase+(result.entries.length-e.position)*B.prizeStep:0)*category(s).cost,'prize','Premiação de '+s.riders.find(r=>r.id===e.riderId).name);if(e.status==='RETIRED')transaction(s,-B.repairCost*category(s).cost,'parts','Reparos após abandono');if(e.position<=3&&e.status==='FINISHED'){const contract=activeContracts(s,'rider').find(c=>c.entityId===e.riderId);transaction(s,-contract.bonus,'bonus','Bônus de pódio do piloto');}}}
 for(const c of s.contracts.filter(c=>c.status==='ACTIVE')){if(c.kind==='sponsor'){transaction(s,c.value,'sponsor','Parcela de '+c.entityId);const sponsor=SPONSORS.find(x=>x.id===c.entityId);for(const e of result.entries.filter(e=>e.teamId==='player'&&e.status==='FINISHED'&&e.position<=sponsor.target))transaction(s,sponsor.bonus*category(s).cost,'sponsorBonus','Meta esportiva de '+sponsor.name);}else transaction(s,-c.value,c.kind==='supplier'?'supplier':'salary','Parcela contratual: '+c.entityId,c.teamId);}
 transaction(s,-B.operatingCost*category(s).cost*(s.team.philosophy==='lean'?.8:1),'operations','Operação da etapa');if(s.debt)transaction(s,-s.debt*B.creditInterest,'interest','Juros de crédito');const player=result.entries.filter(e=>e.teamId==='player');const earned=player.reduce((a,e)=>a+e.points,0);s.team.reputation=clamp(s.team.reputation+(earned>=16?3:earned?1:-1),0,100);s.team.morale=clamp(s.team.morale+(earned>=10?3:-2),10,100);s.results.push(result);s.phase='result';s.session=null;news(s,'Bandeirada em '+currentCircuit(s).name,`${s.riders.find(r=>r.id===result.entries[0].riderId).name} ${result.entries[0].status==='FINISHED'?'vence':'lidera a classificação'}; sua equipe soma ${earned} pontos. Receitas e despesas lançadas no caixa.`);for(const p of s.projects.filter(p=>p.status==='ACTIVE')){p.remaining--;if(p.remaining===0){const ok=random(s)>B.projectRisk;p.status=ok?'COMPLETE':'FAILED';p.gain=ok?B.upgradeGain+Math.floor(random(s)*2):0;s.upgrades[p.attribute]+=p.gain;news(s,ok?'Atualização validada':'Projeto reprovado',`${p.name}: ${ok?'ganho técnico de '+p.gain:'os testes não confirmaram o ganho esperado'}.`);}}
 return result;
}
export function advance(s){if(s.phase!=='result')throw Error('Conclua a corrida primeiro.');s.round++;s.weekend=null;if(s.round>=s.calendar.length){s.phase='seasonEnd';s.history.push({season:s.season,champion:standings(s)[0].id,teamChampion:standings(s,true)[0].id,points:s.teamStandings.player||0,cash:cash(s)});news(s,'Temporada concluída','O campeonato foi encerrado. Revise os resultados e prepare os contratos para o próximo ano.');}else{s.phase='management';rivalMarket(s);} }
export function rivalMarket(s){for(const t of s.teams){const occupied=lineup(s,t.id);const free=s.riders.filter(r=>!s.contracts.some(c=>c.kind==='rider'&&c.entityId===r.id&&c.status==='ACTIVE'));const best=free.sort((a,b)=>b.attributes.speed-a.attributes.speed)[0];const worst=occupied.sort((a,b)=>a.attributes.speed-b.attributes.speed)[0];if(best&&(occupied.length<2||best.attributes.speed>worst.attributes.speed+4)&&cash(s,t.id)>best.salary*category(s).cost*5){if(occupied.length>=2){const c=activeContracts(s,'rider',t.id).find(c=>c.entityId===worst.id);transaction(s,-c.value*2,'termination','Troca de piloto',t.id);c.status='TERMINATED';}negotiate(s,{kind:'rider',id:best.id,value:quote(s,'rider',best.id),teamId:t.id});news(s,'Movimento no mercado',`${t.name} contratou ${best.name}.`);}}
}
export function nextSeason(s){if(s.phase!=='seasonEnd')throw Error('A temporada não terminou.');s.season++;s.round=0;s.phase='management';s.standings={};s.teamStandings={};s.results=[];for(const c of s.contracts)if(c.status==='ACTIVE'&&c.endSeason<s.season){c.status='EXPIRED';if(c.kind==='supplier')s.team.manufacturer=null;}for(const r of s.riders){r.age++;if(r.age<27)r.attributes.speed=Math.min(r.potential,r.attributes.speed+Math.round(random(s)*2*(s.team.philosophy==='youth'?1.5:1)));}for(const t of s.teams)transaction(s,3000000*category(s).cost,'investment','Orçamento de temporada',t.id);transaction(s,700000*category(s).cost,'investment','Aporte anual dos investidores');rivalMarket(s);rivalMarket(s);news(s,'Temporada '+s.season,'Contratos vencidos foram liberados. Renove seu elenco e parceiros antes da estreia.');}
export function develop(s,attribute){if(s.phase!=='management')throw Error('Inicie projetos entre etapas.');if(!Object.hasOwn(s.upgrades,attribute))throw Error('Domínio técnico inválido.');if(s.projects.some(p=>p.status==='ACTIVE'))throw Error('Sua equipe suporta um projeto por vez.');if(staffSkill(s,'engineer')===40)throw Error('Contrate engenharia.');const cost=B.upgradeCost*category(s).cost*(s.team.philosophy==='technical'?.85:1);spend(s,cost,'development','Projeto '+attribute);s.projects.push({id:s.projects.length,name:attribute,attribute,cost,remaining:B.upgradeRounds,status:'ACTIVE',gain:null});news(s,'Engenharia em ação','Projeto iniciado; validação em duas etapas. Existe risco técnico de reprovação.');}
